#include "InmarsatAdsc.h"
#include "InmarsatAero.h"
#include "InmarsatAudio.h"
#include "AeroCodec.h"
#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_approx.hpp>
#include <QFile>
#include <QTemporaryDir>
#include <QtEndian>
#include <array>
#include <cmath>
#include <numbers>
#include <future>

TEST_CASE("Aero ADS-C independent JAERO report and bad CRC", "[inmarsat][native]") {
    // JAERO arincparse.cpp independent example; not generated by our parser.
    const std::string example="F58ADL0040/AKLCDYA.ADS.N705DN07EEE19454DAC7D010D21D0DEEEC44556208024029F0588C71D7884D000E13B90F00000F12C1A280001029305F1019F4";
    const auto p=InmarsatAdsc::parse(example);
    REQUIRE(p);
    CHECK(p->registration=="N705DN");
    CHECK(p->latitude==Catch::Approx(-24.073448181152344));
    CHECK(p->longitude==Catch::Approx(-165.08417129516602));
    CHECK(p->altitudeFt==32000);CHECK(p->secondsPastHour==1076.5);
    for(size_t i=example.find("07EEE");i<example.size();++i) {
        auto bad=example;bad[i]=bad[i]=='0'?'1':'0';
        CHECK_FALSE(InmarsatAdsc::parse(bad));
    }
    for(size_t i=0;i<example.size();++i) CHECK_FALSE(InmarsatAdsc::parse(example.substr(0,i)));
    CHECK_FALSE(InmarsatAdsc::parse("AES=123456 LAT=-34 LON=151"));
}
TEST_CASE("Aero channelizer is continuous across arbitrary chunks", "[inmarsat][native]") {
    for(double rate:{48000.,96000.,192000.}) {
        InmarsatChannelizer whole(rate,2000),chunks(rate,2000);
        std::vector<std::complex<float>> iq(static_cast<size_t>(rate/5));
        for(size_t i=0;i<iq.size();++i) iq[i]=std::polar(0.5f,float(2*std::numbers::pi*3000*i/rate));
        const auto expected=whole.process(iq);
        std::vector<int16_t> actual;
        for(size_t i=0;i<iq.size();i+=137) {
            const auto out=chunks.process({iq.data()+i,std::min<size_t>(137,iq.size()-i)});
            actual.insert(actual.end(),out.begin(),out.end());
        }
        REQUIRE(actual==expected); REQUIRE(actual.size()>9000);
        // +3k RF translated by -2k, then +8k real IF: 9k tone.
        int crossings=0;for(size_t i=101;i<actual.size();++i) if(actual[i-1]<=0 && actual[i]>0)++crossings;
        CHECK(double(crossings)*48000/(actual.size()-101)==Catch::Approx(9000).margin(10));
    }
}
TEST_CASE("Native Aero silence never creates validated frames or audio", "[inmarsat][native]") {
    const std::vector<int16_t> zero(48000*2);
    for(int rate:{600,1200,8400,10500}) {
        InmarsatAero a(rate);size_t emits=0;
        a.setPcmSink([&](auto,uint32_t){++emits;});
        a.processIf(zero);
        CHECK(a.stats().crcOk==0);CHECK(a.stats().voiceWords==0);CHECK(emits==0);
    }
    for(int rate:{1200,10500}) {
        InmarsatAero a(rate,true);a.processIf(zero);
        CHECK(a.stats().crcOk==0);CHECK(a.stats().voiceWords==0);
    }
}
TEST_CASE("Aero codec state is isolated and resets reproducibly", "[inmarsat][native]") {
    std::unique_ptr<SdrAeroCodec,decltype(&sdr_aero_destroy)> a(sdr_aero_create(),sdr_aero_destroy),b(sdr_aero_create(),sdr_aero_destroy);
    REQUIRE(a);REQUIRE(b);
    std::array<uint8_t,12> frame{};
    std::array<int16_t,160> first{},other{};char af[64]{},bf[64]{};
    for(int i=0;i<100;++i) {
        for(size_t k=0;k<frame.size();++k) frame[k]=uint8_t(i*17+k*23);
        CHECK(sdr_aero_decode(a.get(),frame.data(),first.data(),af)==sdr_aero_decode(b.get(),frame.data(),other.data(),bf));
        CHECK(first==other);CHECK(std::string(af)==bf);
    }
    sdr_aero_reset(a.get());sdr_aero_reset(b.get());
    CHECK(sdr_aero_decode(a.get(),frame.data(),first.data(),af)==sdr_aero_decode(b.get(),frame.data(),other.data(),bf));
    CHECK(first==other);
}
TEST_CASE("Aero PCM WAV is exact 8k mono and never overwrites", "[inmarsat][native]") {
    QTemporaryDir dir; const auto path=dir.filePath("voice.wav");
    const std::array<int16_t,4> samples{0,32767,-32768,-1};
    InmarsatAudio audio(false,path);audio.push(samples);audio.finish();
    QFile wav(path);REQUIRE(wav.open(QIODevice::ReadOnly));const auto bytes=wav.readAll();
    REQUIRE(bytes.size()==52);CHECK(bytes.mid(0,4)=="RIFF");
    CHECK(qFromLittleEndian<uint32_t>(bytes.data()+24)==8000);
    CHECK(qFromLittleEndian<uint32_t>(bytes.data()+40)==8);
    for(size_t i=0;i<samples.size();++i)CHECK(qFromLittleEndian<int16_t>(bytes.data()+44+2*i)==samples[i]);
    CHECK_THROWS(InmarsatAudio(false,path));
}
TEST_CASE("Concurrent Aero streams have independent ECC and synthesis", "[inmarsat][native]") {
    auto decode=[] {
        std::unique_ptr<SdrAeroCodec,decltype(&sdr_aero_destroy)> c(sdr_aero_create(),sdr_aero_destroy);
        std::vector<int16_t> result;std::array<uint8_t,12> frame{};std::array<int16_t,160> pcm{};char flags[64]{};
        for(int i=0;i<100;++i){for(int k=0;k<12;++k)frame[k]=uint8_t(i*17+k*23);sdr_aero_decode(c.get(),frame.data(),pcm.data(),flags);result.insert(result.end(),pcm.begin(),pcm.end());}
        return result;
    };
    const auto expected=decode();
    auto a=std::async(std::launch::async,decode),b=std::async(std::launch::async,decode);
    CHECK(a.get()==expected);CHECK(b.get()==expected);
}

TEST_CASE("Aero audio diagnostics distinguish no PCM from silence and muted output", "[inmarsat][native]") {
    InmarsatAudio audio(false, {});
    CHECK(audio.report()["pcmReceived"] == 0);
    CHECK_FALSE(audio.report()["speakerRequested"].get<bool>());
    std::array<int16_t,160> silence{};
    audio.push(silence);
    CHECK(audio.report()["pcmReceived"] == 160);
    CHECK(audio.report()["pcmNonzero"] == 0);
    CHECK(audio.report()["pcmRms"] == 0.0);
    const std::array<int16_t,4> pcm{0,32767,-32768,-1};
    audio.push(pcm);
    audio.discardPlayback();
    const auto report = audio.report();
    CHECK(report["pcmReceived"] == 164);
    CHECK(report["pcmNonzero"] == 3);
    CHECK(report["pcmPeak"] == 32768);
    CHECK(report["pcmRms"].get<double>() == Catch::Approx(std::sqrt((32767.0*32767+32768.0*32768+1)/164)));
    CHECK(report["speakerConsumed"] == 0);
    CHECK(report["speakerQueued"] == 0);
    CHECK_FALSE(report["speakerRunning"].get<bool>());
    CHECK_FALSE(report["speakerFailed"].get<bool>());
}
