"""DEC-0177: bounded ASN.1 per-file notice and embedded-data evidence."""
import hashlib
from pathlib import Path
import re

from package_inventory import json_bytes, parse_json, require, safe_name, tree_files
from stage_runtime import plain

EVIDENCE = 'licenses/embedded-inputs.json'
NOTICES = 'licenses/acars/ASN1-NOTICES.txt'
ASN_ROOT = 'external/acars/libacars/asn1'
# Build-time limits; not restrictions on RF streams or user data.
MAX_FILE = 2 * 1024 * 1024
MAX_TOTAL = 16 * 1024 * 1024
MAX_SOURCES = 1024
MAX_HEADER = 16384
SCOPE = 'ASN.1 source notice and selected data inputs; not a complete SBOM, source kit or linker map'
COPIES = {
    'external/acars/UPSTREAM-README.md': 'licenses/acars/UPSTREAM-README.md',
    'external/acars/LICENSE.md': 'licenses/acars/LICENSE.md',
    'resources/icao/LICENSE-CC0.txt': 'licenses/icao/LICENSE-CC0.txt',
    'resources/icao/README.md': 'licenses/icao/README.md',
    'resources/maps/README.md': 'licenses/aero/NaturalEarth.txt',
    **{f'data/inmarsat/{n}': f'data/inmarsat/{n}'
       for n in ('README.md', '3f5.json', '4f2.json', '4f3.json', '6f1.json', 'i4a.json')},
}
EMBEDDED = ('include/InmarsatIcaoCountry.h', 'resources/maps/ne_110m_land.geojson',
            'resources/inmarsat_map.qrc')
# These three files have no leading notice in pinned libacars 9af09a0 either.
# Verified against that upstream revision; hashes normalize CRLF only.
HEADERLESS = {
    'constraints.c': '57e22c9be98e1d90c42d60055af7a2b117556558c8970ddc6b2af8aa024c98d0',
    'per_decoder.c': '0dc8dfa67aaac270c2d5b427928cfd6e0713e5c090f3a28a7d1a35ccdcbff669',
    'per_encoder.c': 'ed37f807ca1678e1e6a151d26945375648c28b2e8ff28815a70a6ef7ac80ffba',
}


def digest(data):
    return hashlib.sha256(data).hexdigest()


def fingerprint(data):
    return {'sha256': digest(data), 'size': len(data)}


def leading_header(data):
    require(0 < len(data) <= MAX_FILE, 'Embedded input size limit exceeded')
    # Preserve comment contents, including each copyright holder/year, instead
    # of substituting a guessed umbrella license. Only CRLF is normalized.
    text = data[:MAX_HEADER].decode('utf-8').replace('\r\n', '\n')
    match = re.match(r'\s*(/\*.*?\*/)', text, re.S)
    require(match is not None, 'Missing/bounded ASN.1 leading header')
    header = match[1]
    if 'Copyright' in header and 'BSD license' in header:
        return header, 'copyright'
    require('Generated by asn1c-' in header and 'From ASN.1 module' in header,
            'Unreviewed ASN.1 leading header')
    return header, 'generated'


def notice_text(doc):
    lines = ['ASN.1 per-file notices (DEC-0177)', '',
             'Full BSD terms: UPSTREAM-README.md. libacars terms: LICENSE.md.',
             'Generated-schema headers and all inspected file hashes: ../embedded-inputs.json.',
             'This list covers the inspected source tree, not linker reachability.', '',
             'The following upstream files have no leading notice; no notice is invented:',
             *sorted(n for n, r in doc['sources'].items() if r['kind'] == 'headerless'), '']
    for key, header in sorted(doc['headers'].items()):
        paths = sorted(n for n, r in doc['sources'].items()
                       if r.get('header') == key and r.get('kind') == 'copyright')
        if paths:
            lines += paths + ['', header, '']
    return ('\n'.join(lines) + '\n').encode('utf-8')


def collect(repo, source_commit):
    repo = plain(repo, directory=True)
    files = tree_files(plain(repo / ASN_ROOT, directory=True))
    require(len(files) <= MAX_SOURCES, 'Embedded source count limit exceeded')
    sources, headers, copies, total = {}, {}, {}, 0
    names = [*COPIES, *EMBEDDED]
    for name in files:
        require(name in ('CMakeLists.inc', 'CMakeLists.txt') or
                re.fullmatch(r'[A-Za-z0-9_]+\.[ch]', name), 'Unreviewed ASN.1 source input')
        names.append(f'{ASN_ROOT}/{name}')
    require(len(names) <= MAX_SOURCES, 'Embedded source count limit exceeded')
    for name in sorted(names):
        path = plain(repo / name)
        require(0 < path.stat().st_size <= MAX_FILE, 'Embedded input size limit exceeded')
        with path.open('rb') as stream:
            data = stream.read(MAX_FILE + 1)
        total += len(data)
        require(0 < len(data) <= MAX_FILE and total <= MAX_TOTAL, 'Embedded input size limit exceeded')
        record = fingerprint(data)
        if name.startswith(ASN_ROOT + '/') and name.endswith(('.c', '.h')):
            if path.name in HEADERLESS:
                normalized = digest(data.replace(b'\r\n', b'\n'))
                require(normalized == HEADERLESS[path.name], 'Changed reviewed headerless source')
                record.update(kind='headerless', reviewedTextSha256=normalized)
            else:
                try:
                    header, kind = leading_header(data)
                except ValueError as exc:
                    raise ValueError(f'{name}: {exc}') from exc
                key = digest(header.encode('utf-8'))
                headers[key] = header
                record.update(header=key, kind=kind)
        else:
            record['kind'] = 'input'
        sources[name] = record
        if name in COPIES:
            copies[COPIES[name]] = data
    doc = {'schema': 1, 'sourceCommit': source_commit, 'scope': SCOPE,
           'sources': sources, 'headers': headers}
    copies[EVIDENCE] = json_bytes(doc)
    copies[NOTICES] = notice_text(doc)
    verify(copies[EVIDENCE], copies[NOTICES], source_commit,
           {n: fingerprint(b) for n, b in copies.items()})
    return copies


def verify(evidence, notices, source_commit, entries):
    doc = parse_json(evidence)
    require(isinstance(doc, dict) and set(doc) == {'schema', 'sourceCommit', 'scope', 'sources', 'headers'}
            and doc['schema'] == 1 and doc['scope'] == SCOPE
            and doc['sourceCommit'] == source_commit
            and isinstance(source_commit, str) and re.fullmatch(r'[0-9a-f]{40}', source_commit),
            'Invalid embedded evidence identity')
    sources, headers = doc['sources'], doc['headers']
    require(isinstance(sources, dict) and isinstance(headers, dict) and
            0 < len(headers) <= len(sources) <= MAX_SOURCES, 'Embedded source count limit exceeded')
    required = {*COPIES, *EMBEDDED, f'{ASN_ROOT}/CMakeLists.inc', f'{ASN_ROOT}/CMakeLists.txt'}
    require(required <= sources.keys(), 'Missing embedded source input')
    total, kinds, referenced, names = 0, [], set(), set()
    for name, record in sources.items():
        safe_name(name)
        require(name.lower() not in names, 'Colliding embedded source input')
        names.add(name.lower())
        asn = name.startswith(ASN_ROOT + '/') and re.fullmatch(r'[A-Za-z0-9_]+\.[ch]', name[len(ASN_ROOT) + 1:])
        require(name in required or asn, 'Unreviewed embedded source input')
        no_header = asn and name.rsplit('/', 1)[-1] in HEADERLESS
        fields = {'sha256', 'size', 'kind'}
        if asn:
            fields.add('reviewedTextSha256' if no_header else 'header')
        require(isinstance(record, dict) and set(record) == fields,
                'Invalid embedded source record')
        require(isinstance(record['sha256'], str) and re.fullmatch(r'[0-9a-f]{64}', record['sha256'])
                and type(record['size']) is int and 0 < record['size'] <= MAX_FILE,
                'Invalid embedded source fingerprint')
        total += record['size']
        if no_header:
            require(record['kind'] == 'headerless' and
                    record['reviewedTextSha256'] == HEADERLESS[name.rsplit('/', 1)[-1]],
                    'Changed reviewed headerless source')
            kinds.append('headerless')
        elif asn:
            key = record['header']
            require(isinstance(key, str) and key in headers and isinstance(headers[key], str),
                    'Missing embedded source header')
            encoded = headers[key].encode('utf-8')
            require(len(encoded) < MAX_HEADER and digest(encoded) == key, 'Embedded header hash mismatch')
            header, kind = leading_header(encoded)
            require(header == headers[key] and kind == record['kind'], 'Embedded header classification mismatch')
            kinds.append(kind)
            referenced.add(key)
        else:
            require(record['kind'] == 'input', 'Invalid embedded input kind')
        if name in COPIES:
            entry = entries.get(COPIES[name], {})
            require(all(entry.get(k) == record[k] for k in ('sha256', 'size')),
                    f'Packaged embedded input mismatch: {COPIES[name]}')
    require(total <= MAX_TOTAL, 'Embedded input size limit exceeded')
    require(set(headers) == referenced and {'copyright', 'generated'} <= set(kinds),
            'Incomplete/unreferenced ASN.1 headers')
    require(notices == notice_text(doc), 'ASN.1 notice text mismatch')
    return {'asnSources': len(kinds), 'copyrightFiles': kinds.count('copyright'),
            'generatedFiles': kinds.count('generated'), 'headerlessFiles': kinds.count('headerless'),
            'dataAndBuildInputs': len(sources) - len(kinds)}
