#!/usr/bin/env python3
"""Offline WAV -> text helper for SDR Town Decode Log.

Usage:
  python scripts/stt_transcribe_wav.py path/to/segment.wav
  python scripts/stt_transcribe_wav.py --probe

Prints transcript text to stdout. Exit non-zero on failure.
Requires one backend:
  pip install openai-whisper
  pip install faster-whisper
Optional env:
  SDR_TOWN_STT_BACKEND     (auto, openai-whisper, faster-whisper)
  SDR_TOWN_WHISPER_MODEL   (default: base.en)
  SDR_TOWN_WHISPER_DEVICE  (default: cpu)
  SDR_TOWN_WHISPER_COMPUTE (default: int8; faster-whisper only)
  SDR_TOWN_STT_ALLOW_UNSAFE_FAST_WHISPER=1

On Windows, auto prefers openai-whisper when both backends are installed.
Some faster-whisper/ctranslate2 builds import successfully but can access-violate
on the short float WAVs generated by the P25 replay harness.
"""

from __future__ import annotations

import os
import subprocess
import struct
import sys
import tempfile
import wave
import contextlib
import importlib
import io
from math import gcd
from pathlib import Path


def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass


def _riff_chunks(data: bytes):
    if len(data) < 12 or data[0:4] != b"RIFF" or data[8:12] != b"WAVE":
        raise ValueError("not a RIFF/WAVE file")
    pos = 12
    while pos + 8 <= len(data):
        chunk_id = data[pos : pos + 4]
        size = struct.unpack_from("<I", data, pos + 4)[0]
        start = pos + 8
        end = min(start + size, len(data))
        yield chunk_id, data[start:end]
        pos = end + (size & 1)


def _prepare_whisper_wav(wav: Path) -> tuple[Path, Path | None]:
    data = wav.read_bytes()
    fmt = None
    audio = None
    for chunk_id, chunk in _riff_chunks(data):
        if chunk_id == b"fmt ":
            fmt = chunk
        elif chunk_id == b"data":
            audio = chunk
    if fmt is None or audio is None or len(fmt) < 16:
        return wav, None

    audio_format, channels, sample_rate, _byte_rate, _align, bits = struct.unpack_from("<HHIIHH", fmt, 0)
    if audio_format != 3 or bits != 32:
        return wav, None

    floats = struct.iter_unpack("<f", audio[: len(audio) - (len(audio) % 4)])
    pcm = bytearray()
    for (sample,) in floats:
        sample = max(-1.0, min(1.0, sample))
        pcm += struct.pack("<h", int(round(sample * 32767.0)))

    tmp = tempfile.NamedTemporaryFile(prefix="sdrtown_stt_", suffix=".pcm16.wav", delete=False)
    tmp_path = Path(tmp.name)
    tmp.close()
    with wave.open(str(tmp_path), "wb") as out:
        out.setnchannels(channels)
        out.setsampwidth(2)
        out.setframerate(sample_rate)
        out.writeframes(bytes(pcm))
    return tmp_path, tmp_path


def _normalise_backend(value: str | None) -> str:
    backend = (value or "auto").strip().lower().replace("_", "-")
    aliases = {
        "openai": "openai-whisper",
        "whisper": "openai-whisper",
        "faster": "faster-whisper",
        "fasterwhisper": "faster-whisper",
    }
    return aliases.get(backend, backend)


def _module_available(module_name: str) -> bool:
    try:
        with contextlib.redirect_stderr(io.StringIO()):
            __import__(module_name)
        return True
    except Exception:
        return False


def _backend_candidates(requested: str | None) -> list[str]:
    backend = _normalise_backend(requested or os.environ.get("SDR_TOWN_STT_BACKEND"))
    if backend == "auto":
        # Prefer the stable backend for this platform.  On Windows, field replay
        # WAVs have triggered ctranslate2 access violations in faster-whisper
        # even though import/probe succeeds; openai-whisper handles the same
        # float WAVs reliably through the in-process resampler path.  Still keep
        # faster-whisper as a fallback: scripts/setup_stt.ps1 installs it in the
        # project venv, and dropping it from auto mode disables clear-audio
        # automation on clean test machines.
        if sys.platform.startswith("win"):
            allow_unsafe_fast = os.environ.get("SDR_TOWN_STT_ALLOW_UNSAFE_FAST_WHISPER", "").strip().lower()
            if allow_unsafe_fast in {"1", "true", "yes", "on"}:
                return ["openai-whisper", "faster-whisper"]
            return ["openai-whisper", "faster-whisper"]
        return ["faster-whisper", "openai-whisper"]
    return [backend]


def _fast_whisper_child_mode_enabled() -> bool:
    return os.environ.get("SDR_TOWN_STT_FAST_WHISPER_CHILD", "").strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def _allow_unsafe_fast_whisper() -> bool:
    return os.environ.get("SDR_TOWN_STT_ALLOW_UNSAFE_FAST_WHISPER", "").strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def _backend_probe_error(backend: str) -> str | None:
    try:
        with contextlib.redirect_stderr(io.StringIO()):
            if backend == "openai-whisper":
                importlib.import_module("whisper")
                import numpy as np
                import torch

                # Torch can import successfully while NumPy support is broken
                # (common with NumPy 2.x + older wheels).  Whisper then fails at
                # transcription time with "Numpy is not available"; catch that
                # during probe so auto mode can try the next backend.
                torch.from_numpy(np.zeros(1, dtype=np.float32))
                return None
            if backend == "faster-whisper":
                importlib.import_module("faster_whisper")
                return None
    except Exception as ex:  # noqa: BLE001
        return str(ex) or ex.__class__.__name__
    return f"unsupported STT backend: {backend}"


def _select_backend(requested: str | None) -> str:
    for backend in _backend_candidates(requested):
        if _backend_probe_error(backend) is None:
            return backend
    return "missing"


def _transcribe_with_backend(backend: str, wav: Path) -> str:
    if backend == "openai-whisper":
        return _transcribe_openai_whisper(wav)
    if backend == "faster-whisper":
        return _transcribe_faster_whisper(wav)
    raise ValueError(f"unsupported STT backend: {backend}")


def _transcribe_faster_whisper_isolated(wav: Path) -> tuple[str | None, str | None]:
    env = os.environ.copy()
    env["SDR_TOWN_STT_FAST_WHISPER_CHILD"] = "1"
    env["SDR_TOWN_STT_ALLOW_UNSAFE_FAST_WHISPER"] = "1"
    timeout_s = 120.0
    try:
        timeout_s = float(env.get("SDR_TOWN_STT_TIMEOUT_SEC", "120"))
    except ValueError:
        timeout_s = 120.0

    cmd = [
        sys.executable,
        str(Path(__file__).resolve()),
        "--backend",
        "faster-whisper",
        str(wav),
    ]
    try:
        completed = subprocess.run(
            cmd,
            env=env,
            text=True,
            capture_output=True,
            timeout=max(5.0, timeout_s),
            check=False,
        )
    except subprocess.TimeoutExpired as ex:
        return None, f"faster-whisper child timed out after {ex.timeout}s"
    except Exception as ex:  # noqa: BLE001
        return None, f"faster-whisper child launch failed: {ex}"

    if completed.returncode == 0:
        return completed.stdout.strip(), None
    detail = (completed.stderr or completed.stdout or "").strip()
    if not detail:
        detail = "process crashed" if completed.returncode < 0 else "process failed"
    return None, f"faster-whisper child exited {completed.returncode}: {detail}"


def _load_wav_mono_float32(wav: Path):
    import numpy as np

    data = wav.read_bytes()
    fmt = None
    audio = None
    for chunk_id, chunk in _riff_chunks(data):
        if chunk_id == b"fmt ":
            fmt = chunk
        elif chunk_id == b"data":
            audio = chunk
    if fmt is None or audio is None or len(fmt) < 16:
        raise ValueError("missing fmt/data RIFF chunks")

    audio_format, channels, sample_rate, _byte_rate, _align, bits = struct.unpack_from("<HHIIHH", fmt, 0)
    channels = max(1, int(channels))
    if audio_format == 3 and bits == 32:
        samples = np.frombuffer(audio[: len(audio) - (len(audio) % 4)], dtype="<f4").astype(np.float32, copy=False)
    elif audio_format == 1 and bits == 16:
        samples = np.frombuffer(audio[: len(audio) - (len(audio) % 2)], dtype="<i2").astype(np.float32) / 32768.0
    elif audio_format == 1 and bits == 32:
        samples = np.frombuffer(audio[: len(audio) - (len(audio) % 4)], dtype="<i4").astype(np.float32) / 2147483648.0
    else:
        raise ValueError(f"unsupported WAV format={audio_format} bits={bits}")

    frame_count = samples.size // channels
    if frame_count <= 0:
        return np.zeros(0, dtype=np.float32)
    samples = samples[: frame_count * channels].reshape(frame_count, channels)
    mono = samples[:, 0] if channels == 1 else samples.mean(axis=1)
    mono = np.clip(mono.astype(np.float32, copy=False), -1.0, 1.0)
    if sample_rate == 16000:
        return mono

    try:
        from scipy.signal import resample_poly

        div = gcd(int(sample_rate), 16000)
        return resample_poly(mono, 16000 // div, int(sample_rate) // div).astype(np.float32, copy=False)
    except Exception:
        if mono.size == 0:
            return mono
        duration = mono.size / float(sample_rate)
        out_len = max(1, int(round(duration * 16000.0)))
        src_x = np.linspace(0.0, duration, num=mono.size, endpoint=False)
        dst_x = np.linspace(0.0, duration, num=out_len, endpoint=False)
        return np.interp(dst_x, src_x, mono).astype(np.float32)


def _transcribe_openai_whisper(wav: Path) -> str:
    import whisper

    model_name = os.environ.get("SDR_TOWN_WHISPER_MODEL", "base.en")
    device = os.environ.get("SDR_TOWN_WHISPER_DEVICE", "cpu")
    audio = _load_wav_mono_float32(wav)
    if audio.size == 0:
        return ""
    model = whisper.load_model(model_name, device=device)
    result = model.transcribe(
        audio,
        language="en",
        fp16=False,
        verbose=False,
        condition_on_previous_text=False,
    )
    return str(result.get("text", "")).strip()


def _transcribe_faster_whisper(wav: Path) -> str:
    from faster_whisper import WhisperModel

    model_name = os.environ.get("SDR_TOWN_WHISPER_MODEL", "base.en")
    device = os.environ.get("SDR_TOWN_WHISPER_DEVICE", "cpu")
    compute = os.environ.get("SDR_TOWN_WHISPER_COMPUTE", "int8")

    temp_wav = None
    try:
        transcribe_wav, temp_wav = _prepare_whisper_wav(wav)
        model = WhisperModel(model_name, device=device, compute_type=compute)
        segments, _info = model.transcribe(
            str(transcribe_wav),
            language="en",
            vad_filter=True,
            beam_size=1,
            best_of=1,
        )
        parts = []
        for seg in segments:
            t = (seg.text or "").strip()
            if t:
                parts.append(t)
        return " ".join(parts).strip()
    finally:
        if temp_wav is not None:
            try:
                temp_wav.unlink()
            except OSError:
                pass


def _parse_args(argv: list[str]) -> tuple[str | None, bool, Path | None]:
    backend = None
    probe = False
    wav = None
    i = 1
    while i < len(argv):
        arg = argv[i]
        if arg == "--probe":
            probe = True
        elif arg.startswith("--backend="):
            backend = arg.split("=", 1)[1]
        elif arg == "--backend":
            i += 1
            if i >= len(argv):
                raise ValueError("--backend requires a value")
            backend = argv[i]
        elif wav is None:
            wav = Path(arg)
        else:
            raise ValueError(f"unexpected argument: {arg}")
        i += 1
    return backend, probe, wav


def main(argv: list[str]) -> int:
    _configure_stdio()
    try:
        requested_backend, probe, wav = _parse_args(argv)
    except ValueError as ex:
        print(str(ex), file=sys.stderr)
        return 2

    requested_is_auto = _normalise_backend(requested_backend or os.environ.get("SDR_TOWN_STT_BACKEND")) == "auto"
    backends = _backend_candidates(requested_backend)
    backend = _select_backend(requested_backend)
    if probe:
        errors = {candidate: _backend_probe_error(candidate) for candidate in backends}
        available = [candidate for candidate, error in errors.items() if error is None]
        if not available:
            print("no supported STT backend found", file=sys.stderr)
            for candidate, error in errors.items():
                print(f"{candidate} probe failed: {error}", file=sys.stderr)
            return 3
        print(f"ok {available[0]}")
        return 0

    if wav is None:
        print("usage: stt_transcribe_wav.py [--backend <backend>] <wav>", file=sys.stderr)
        return 2
    if not wav.is_file():
        print(f"missing wav: {wav}", file=sys.stderr)
        return 2

    if backend == "missing":
        print("no supported STT backend found", file=sys.stderr)
        return 3

    errors: list[str] = []
    for candidate in backends:
        probe_error = _backend_probe_error(candidate)
        if probe_error is not None:
            errors.append(f"{candidate} probe failed: {probe_error}")
            if not requested_is_auto:
                break
            continue
        try:
            if (
                requested_is_auto
                and candidate == "faster-whisper"
                and sys.platform.startswith("win")
                and not _allow_unsafe_fast_whisper()
                and not _fast_whisper_child_mode_enabled()
            ):
                text, child_error = _transcribe_faster_whisper_isolated(wav)
                if child_error is not None:
                    errors.append(child_error)
                    continue
                text = text or ""
            else:
                text = _transcribe_with_backend(candidate, wav)
            sys.stdout.write(text + ("\n" if text else ""))
            return 0
        except Exception as ex:  # noqa: BLE001
            errors.append(f"{candidate} transcribe failed: {ex}")
            if not requested_is_auto:
                break

    for error in errors:
        print(error, file=sys.stderr)
    return 4


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
