"""DEC-0177: exact notice/data coverage and fail-closed packaging fixtures."""
import copy
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

import embedded_notices as embedded
from package_inventory import json_bytes, parse_json

COPYRIGHT = b'/*\r\n * Copyright (c) Example Holder\r\n * Redistribution subject to BSD license.\r\n */\r\n'
GENERATED = b'/*\n * Generated by asn1c-0.9.28\n * From ASN.1 module "Example"\n */\n'


def seed(repo):
    payloads = {name: b'fixture input\n' for name in (*embedded.COPIES, *embedded.EMBEDDED)}
    payloads.update({f'{embedded.ASN_ROOT}/CMakeLists.txt': b'fixture build recipe\n',
                     f'{embedded.ASN_ROOT}/CMakeLists.inc': b'fixture build inputs\n',
                     f'{embedded.ASN_ROOT}/sample.c': COPYRIGHT + b'int x;\n',
                     f'{embedded.ASN_ROOT}/sample.h': COPYRIGHT,
                     f'{embedded.ASN_ROOT}/Generated.c': GENERATED + b'int generated;\n'})
    for name, data in payloads.items():
        target = repo / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)


class EmbeddedTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.repo = Path(self.temp.name).resolve()
        self.sha = '1' * 40
        seed(self.repo)

    def verify(self, copies):
        return embedded.verify(copies[embedded.EVIDENCE], copies[embedded.NOTICES], self.sha,
                               {n: embedded.fingerprint(b) for n, b in copies.items()})

    def test_exact_copies_deterministic_grouped_notices_and_privacy(self):
        (self.repo / 'private.iq').write_bytes(b'not eligible')
        first = embedded.collect(self.repo, self.sha)
        self.assertEqual(first, embedded.collect(self.repo, self.sha))
        result = self.verify(first)
        self.assertEqual(result['asnSources'], 3)
        self.assertEqual(result['copyrightFiles'], 2)
        self.assertEqual(result['generatedFiles'], 1)
        self.assertEqual(first[embedded.NOTICES].count(b'Copyright (c) Example Holder'), 1)
        self.assertIn(COPYRIGHT.replace(b'\r\n', b'\n').strip(), first[embedded.NOTICES])
        for name, destination in embedded.COPIES.items():
            self.assertEqual(first[destination], (self.repo / name).read_bytes())
        self.assertNotIn(b'private.iq', first[embedded.EVIDENCE])
        self.assertNotIn(str(self.repo).encode(), first[embedded.EVIDENCE])

    def test_added_source_is_included_and_its_body_hash_changes(self):
        path = self.repo / embedded.ASN_ROOT / 'Another.c'
        path.write_bytes(COPYRIGHT + b'int a;\n')
        first = embedded.collect(self.repo, self.sha)
        self.assertEqual(self.verify(first)['asnSources'], 4)
        path.write_bytes(COPYRIGHT + b'int b;\n')
        second = embedded.collect(self.repo, self.sha)
        self.assertNotEqual(first[embedded.EVIDENCE], second[embedded.EVIDENCE])
        self.assertEqual(first[embedded.NOTICES], second[embedded.NOTICES])

    def test_each_data_or_notice_input_is_required(self):
        for name in (*embedded.COPIES, *embedded.EMBEDDED):
            with self.subTest(name=name):
                path = self.repo / name
                data = path.read_bytes()
                path.unlink()
                with self.assertRaisesRegex(ValueError, 'Missing runtime input'):
                    embedded.collect(self.repo, self.sha)
                path.write_bytes(b'')
                with self.assertRaisesRegex(ValueError, 'size limit'):
                    embedded.collect(self.repo, self.sha)
                path.write_bytes(data)

    def test_unfamiliar_missing_oversized_and_invalid_utf8_headers_rejected(self):
        path = self.repo / embedded.ASN_ROOT / 'sample.c'
        for data in (b'int x;', b'/* Unknown license */', b'/*' + b'x' * embedded.MAX_HEADER,
                     b'/*\xff*/'):
            with self.subTest(data=data[:32]):
                path.write_bytes(data)
                with self.assertRaises(ValueError):
                    embedded.collect(self.repo, self.sha)

    def test_unreviewed_files_and_linked_inputs_rejected(self):
        path = self.repo / embedded.ASN_ROOT / 'private.iq'
        path.write_bytes(b'never collect')
        with self.assertRaisesRegex(ValueError, 'Unreviewed ASN.1 source'):
            embedded.collect(self.repo, self.sha)
        path.unlink()
        with patch('stage_runtime.linked', return_value=True):
            with self.assertRaisesRegex(ValueError, 'Linked runtime'):
                embedded.collect(self.repo, self.sha)
        with patch('package_inventory.linked', return_value=True):
            with self.assertRaisesRegex(ValueError, 'non-linked'):
                embedded.collect(self.repo, self.sha)

    def test_resource_limits(self):
        for setting in ('MAX_FILE', 'MAX_TOTAL', 'MAX_SOURCES'):
            with self.subTest(setting=setting), patch.object(embedded, setting, 1):
                with self.assertRaisesRegex(ValueError, 'limit exceeded'):
                    embedded.collect(self.repo, self.sha)

    def test_all_packaged_input_copies_are_bound_to_source_evidence(self):
        copies = embedded.collect(self.repo, self.sha)
        for name in embedded.COPIES.values():
            with self.subTest(name=name):
                changed = dict(copies, **{name: copies[name] + b'tamper'})
                with self.assertRaisesRegex(ValueError, 'Packaged embedded input mismatch'):
                    self.verify(changed)

    def test_notice_tamper_and_wrong_commit_rejected(self):
        copies = embedded.collect(self.repo, self.sha)
        copies[embedded.NOTICES] += b'tamper'
        with self.assertRaisesRegex(ValueError, 'notice text mismatch'):
            self.verify(copies)
        copies = embedded.collect(self.repo, '2' * 40)
        with self.assertRaisesRegex(ValueError, 'evidence identity'):
            self.verify(copies)

    def test_metadata_tamper_rejected(self):
        copies = embedded.collect(self.repo, self.sha)
        original = parse_json(copies[embedded.EVIDENCE])
        mutations = [lambda d: d.update(scope='certified'),
                     lambda d: d['sources'].pop(embedded.EMBEDDED[0]),
                     lambda d: d['headers'].update(unreferenced='Unknown'),
                     lambda d: d['sources'][f'{embedded.ASN_ROOT}/sample.c'].update(kind='generated'),
                     lambda d: d['sources'][f'{embedded.ASN_ROOT}/sample.c'].update(size=-1),
                     lambda d: d['sources'].update({'../private.iq': {}}),
                     lambda d: d['sources'].update({'private.iq': {}}),
                     lambda d: d['sources'][f'{embedded.ASN_ROOT}/sample.c'].update(header=[])]
        for mutate in mutations:
            doc = copy.deepcopy(original)
            mutate(doc)
            copies[embedded.EVIDENCE] = json_bytes(doc)
            with self.assertRaises(ValueError):
                self.verify(copies)

    def test_reviewed_headerless_file_cannot_change_silently(self):
        path = self.repo / embedded.ASN_ROOT / 'constraints.c'
        path.write_bytes(b'int changed;')
        with self.assertRaisesRegex(ValueError, 'Changed reviewed headerless'):
            embedded.collect(self.repo, self.sha)

    def test_real_checked_out_sources(self):
        repo = Path(__file__).resolve().parents[1]
        copies = embedded.collect(repo, self.sha)
        result = self.verify(copies)
        self.assertGreaterEqual(result['asnSources'], 488)
        self.assertGreaterEqual(result['copyrightFiles'], 59)
        self.assertEqual(result['headerlessFiles'], 3)
        self.assertIn(b'X/IO Labs', copies[embedded.NOTICES])
        self.assertIn(b'Lev Walkin', copies[embedded.NOTICES])
        # Checked against the exact upstream revision; checkout may change CRLF.
        dedication = copies['licenses/icao/LICENSE-CC0.txt'].replace(b'\r\n', b'\n')
        self.assertEqual(embedded.digest(dedication),
                         'a2010f343487d3f7618affe54f789f5487602331c0a8d03f49e9a7c547cf0499')


if __name__ == '__main__':
    unittest.main()
