# DEC-0139: generate defaults, never overwrite a user's remote_diagnostics.json.
# The distribution key grants collector access only. Never supply an admin key.
file(READ "${TEMPLATE}" CONFIG)
set(TOKEN "$ENV{SDR_TOWN_DIAG_RELEASE_TOKEN}")
if(TOKEN_FILE AND EXISTS "${TOKEN_FILE}")
  file(READ "${TOKEN_FILE}" TOKEN)
endif()
string(STRIP "${TOKEN}" TOKEN)
if(REQUIRE_TOKEN AND TOKEN STREQUAL "")
  message(FATAL_ERROR "Release diagnostics credential is missing; refusing an unconfigured asset")
endif()
if(NOT TOKEN STREQUAL "")
  string(LENGTH "${TOKEN}" TOKEN_LENGTH)
  if(TOKEN_LENGTH LESS 16 OR TOKEN_LENGTH GREATER 512 OR TOKEN MATCHES "[^A-Za-z0-9._~-]")
    message(FATAL_ERROR "Invalid collector credential format (value not logged)")
  endif()
  string(JSON CONFIG SET "${CONFIG}" token "\"${TOKEN}\"")
endif()
get_filename_component(DIR "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${DIR}")
file(WRITE "${OUTPUT}.tmp" "${CONFIG}\n")
file(RENAME "${OUTPUT}.tmp" "${OUTPUT}")
