from pathlib import Path
main = Path(__file__).resolve().parents[1] / 'main.cpp'
text = main.read_text()
assert 'takeUndecoded(size_t maxSamples,' in text and 'size_t overlapSamples,' in text, 'Rolling IQ decode must accept overlapSamples'
assert 'absolute dibit de-duplication' in text, 'Overlap rationale/de-duplication comment missing'
assert 'kP25Phase2VoiceDecodeWindowSeconds = 0.720' in text, 'Phase 2 rolling window should cover two full superframes for MAC/ESS recovery'
assert 'kP25Phase2VoiceDecodeFirstColdEyeSeconds = 0.720' in text, 'First traffic eye should cover two full Phase 2 superframes'
assert 'kP25Phase2VoiceDecodeAcquireChunkSeconds = 0.050' in text, 'Post-eye acquire should use short bounded fresh chunks'
assert 'kP25Phase2VoiceDecodeAcquireOverlapSeconds = 0.720' in text, 'Acquire window should keep two-superframe pre-roll while cold locking'
assert 'kP25Phase2VoiceDecodeMinFreshSeconds = 0.020' in text, 'Post-eye acquire should not stall waiting for a full superframe'
assert 'kP25Phase2VoiceDecodeFirstColdEyeSeconds * 0.5' in text, 'First cold eye must still wait for substantial fresh IQ'
assert 'kP25Phase2VoiceDecodeSustainChunkSeconds = 0.120' in text, 'Sustain should advance on short fresh IQ slices'
assert 'kP25Phase2VoiceDecodeSustainMinFreshSeconds = 0.040' in text, 'Sustain should use the 40 ms hop proven by clear-call replay'
assert 'kP25Phase2VoiceDecodeSustainOverlapSeconds = 0.360' in text, 'Locked sustain should keep one-superframe pre-roll without replaying huge RF windows'
assert 'kP25Phase2VoiceDecodeSpeakerSustainOverlapSeconds = 0.240' in text, 'Speaker sustain should use short pre-roll after audio opens to avoid worker-busy burst audio'
assert 'phase2SustainDecodeWindow' in text and 'p25Phase2UseSustainDecodeWindowLocked' in text, 'Phase 2 decode path must switch between acquire and sustained windows'
assert 'hasTrustedCallState && hasStableSuperframeMask' in text, 'Sustain decode must wait for stable TDMA framing before dropping below superframe-sized acquire chunks'
assert 'armedTrafficSource && hasRecentTrafficEvidence' not in text, 'Soft recent traffic evidence must not trigger premature sustain decode'
assert text.count('takeUndecoded(maxDecodeChunk, decodeOverlap, iqStartAbsolute, iqStartAbsoluteKnown') >= 2, 'Both GUI and CLI Phase 2 paths must use overlapped decode windows'
assert 'takeUndecoded(maxDecodeChunk, iqStartAbsolute' not in text, 'Strict non-overlapped Phase 2 decode call remains'
assert 'maxOverlapSamples = (rollingWindow > maxDecodeChunk)' in text, 'Overlap must be capped by rolling-window budget, not by half the fresh chunk'
assert 'maxDecodeChunk / 2' not in text[text.find('const double maxDecodeChunkSeconds'):text.rfind('const size_t minDecodeFreshNominal')], 'Phase 2 overlap is still clamped to half the fresh chunk'
print('P25 Phase 2 overlapped rolling decode regression: PASS')
